name: Test Rakuten Ranking

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Rakuten Smartphone Ranking test
        env:
          RAKUTEN_APPLICATION_ID: ${{ secrets.RAKUTEN_APPLICATION_ID }}
          RAKUTEN_ACCESS_KEY: ${{ secrets.RAKUTEN_ACCESS_KEY }}
        run: |
          echo "========================================"
          echo "SMARTPHONE RANKING"
          echo "========================================"

          curl -G "https://openapi.rakuten.co.jp/ichibaranking/api/IchibaItem/Ranking/20220601" \
            -H "Origin: https://supisho.com" \
            -H "Referer: https://supisho.com/" \
            --data-urlencode "format=json" \
            --data-urlencode "applicationId=$RAKUTEN_APPLICATION_ID" \
            --data-urlencode "accessKey=$RAKUTEN_ACCESS_KEY" \
            --data-urlencode "genreId=560202" \
            --data-urlencode "page=1"

          echo