name: Test Rakuten API

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Item Ranking sample
        env:
          RAKUTEN_APPLICATION_ID: ${{ secrets.RAKUTEN_APPLICATION_ID }}
          RAKUTEN_ACCESS_KEY: ${{ secrets.RAKUTEN_ACCESS_KEY }}
        run: |
          curl -s -G "https://openapi.rakuten.co.jp/ichibaranking/api/IchibaItem/Ranking/20220601" \
            -H "accessKey: ${RAKUTEN_ACCESS_KEY}" \
            -H "Origin: https://supisho.com" \
            -H "Referer: https://supisho.com" \
            --data-urlencode "applicationId=${RAKUTEN_APPLICATION_ID}" \
            --data-urlencode "format=json" \
            --data-urlencode "genreId=564500"